[project]
name = "gitoxide"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=3.4.3",
    "maturin>=1.8.4",
    "pyclean>=3.1.0",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
]
